# === CLI ツール ===
brew "bitwarden-cli"
brew "bat"
brew "delta"
brew "direnv"
brew "eza"
brew "fd"
brew "fswatch"
brew "fzf"
brew "gh"
brew "ghq"
brew "golang-migrate"
brew "jq"
brew "lazygit"
brew "mise"
brew "mkcert"
brew "mysql-client"
brew "pkgconf"
brew "pnpm"
brew "postgresql@17"
brew "rclone"
brew "ripgrep"
brew "uv"
brew "volta"
brew "yq"
brew "zoxide"

# === DB コネクタ ===
brew "mariadb-connector-c"

# === GUI アプリ ===
cask "bitwarden"
cask "bruno"
cask "chatgpt"
cask "codex-app"
cask "docker"
cask "elecom-mouse-util"
cask "gcloud-cli"
cask "ghostty"
cask "karabiner-elements"
cask "kap"
cask "maccy"
cask "obsidian"
cask "raycast"
cask "rectangle"
cask "tableplus"
